# Generated by Django 5.2.1 on 2025-05-27 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'lab',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('registration', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Scheduled',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduled_lab.lab')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduled_lab.teacher')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduled_lab.user')),
            ],
            options={
                'db_table': 'scheduled',
            },
        ),
    ]
